// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { applyDeployConfig } from "./lib/config/deploy";

/**
 * WHERE THE DATABASE URL COMES FROM
 *
 * `config/deploy.yml` — the single file a human edits (Spring Boot
 * `application.yml` style). `applyDeployConfig()` reads it, resolves the active
 * profile, validates it, and projects the result into `process.env.DATABASE_URL`.
 * The app does the identical thing at the top of `next.config.ts`, so the CLI and
 * the app resolve the SAME single value.
 *
 * That projection step is also what loads `.env` for the CLI. The Prisma CLI does
 * NOT load `.env` itself ("Prisma config detected, skipping environment variable
 * loading"), which is why the call above is required — it replaces the bare
 * `import "dotenv/config"` this file used to carry.
 *
 * NOTE ON RESOLUTION (verified on Prisma 6.19.3): the schema's own
 * `url = env("DATABASE_URL")` in `prisma/schema.prisma` is what the CLI actually
 * uses — the `datasource.url` below is inert. Do not "fix" a resolution problem by
 * changing this value; change `config/deploy.yml` (or the profile selected by
 * `DEPLOY_PROFILE`). It is passed through only so this file mirrors the schema and
 * stays type-safe.
 *
 * A malformed `config/deploy.yml` throws from `applyDeployConfig()` with a readable
 * message naming the file and setting. That is deliberate: it is far better to be
 * told `config/deploy.yml: database.host is required` than to have a build proceed
 * and fail later with an opaque connection error.
 */
const { config: deployConfig, warnings } = applyDeployConfig();

for (const warning of warnings) {
  console.warn(`[prisma.config.ts] ${warning}`);
}

const databaseUrl = process.env["DATABASE_URL"];

if (!databaseUrl) {
  // Must be narrowed before it reaches `datasource.url` (a `string`): assigning
  // `string | undefined` there was a TS2322 that aborted `next build` outright.
  // Report it as something a human can act on, and still let the CLI proceed so
  // `prisma generate` (which needs no connection) keeps working.
  console.warn(
    "[prisma.config.ts] DATABASE_URL is not set. Copy config/deploy.example.yml to " +
      "config/deploy.yml and edit the database block; it selects the database and takes " +
      "the password from ${WISESPLIT_DB_PASSWORD} in .env."
  );
} else if (deployConfig) {
  console.log(
    `[prisma.config.ts] profile "${deployConfig.profile}" -> ${deployConfig.database.user}@${deployConfig.database.host}:${deployConfig.database.port}/${deployConfig.database.name}`
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Omitted entirely when unset, rather than defaulted: a fallback here would be a
  // second, silently-diverging source of truth for which database is live. The
  // value above came from `config/deploy.yml` via `applyDeployConfig()`, which is
  // the projection step — not a default.
  ...(databaseUrl ? { datasource: { url: databaseUrl } } : {}),
});
