-- ============================================================================
-- Wisesplit — schema for the online MariaDB database
-- Generated from prisma/schema.prisma (6 models).
--
-- *** THE MONEY COLUMNS ARE THE POST-MIGRATION TARGET, NOT TODAY'S SHAPE. ***
-- The four money columns are DECIMAL(12,2) / DECIMAL(5,2), deliberately NOT
-- DOUBLE. The app cannot read this database correctly until the code refactor
-- lands — Prisma returns DECIMAL as a Decimal OBJECT, not a JS number. See the
-- MONEY section at the foot of this file before pointing the app at it.
-- Every other column matches today's schema exactly.
--
-- TARGET ENGINE: MariaDB 11.1.5 (ubu2204) — see the NOTE AT THE FOOT on that
-- version's support status. Everything below is also valid MySQL 5.7+/8.0, so
-- this file is portable across both — but one collation named in the comments
-- (utf8mb4_0900_ai_ci) exists ONLY in MySQL 8 and is NOT in MariaDB. See
-- point 2.
--
-- Run with:  mariadb -h <host> -u <user> -p <database> < tables.sql
--         or mysql   -h <host> -u <user> -p <database> < tables.sql
-- Or paste into phpMyAdmin / your host's SQL console.
--
-- In Prisma, both engines use the SAME provider — there is no "mariadb"
-- provider. You will write:  provider = "mysql"
-- ============================================================================
--
-- TWO THINGS IN HERE ARE LOAD-BEARING. They are not style choices.
--
-- 1. utf8mb4, NOT utf8.
--    MySQL's legacy "utf8" is a 3-byte encoding and cannot store emoji or many
--    CJK characters. This app stores emoji LITERALLY — Category.emoji holds
--    the icon itself (🍕 🚗 🎉 💰), and group/expense names are free text
--    friends type on holiday. On legacy utf8 those either fail the insert
--    (error 1366) or silently truncate. utf8mb4 is 4-byte and handles all of it.
--
-- 2. utf8mb4_bin collation — do NOT accept the server default.
--    MariaDB's default for utf8mb4 is utf8mb4_general_ci (case-INSENSITIVE).
--    (MySQL 8's default is utf8mb4_0900_ai_ci, which is also case-insensitive
--    — and which does NOT exist in MariaDB at all: importing a dump that names
--    it fails with "Unknown collation: utf8mb4_0900_ai_ci". The collation name
--    differs between engines; the footgun does not.)
--    Two tables carry @@unique([groupId, name]) — GroupMember and Category —
--    and under any case-insensitive collation "Bob" and "bob" COLLIDE, so a
--    second member called "bob" is rejected as a duplicate. It would also make
--    slug/token lookups case-insensitive, which they must not be.
--    SQLite (what you run now) is case-sensitive (BINARY), so utf8mb4_bin is
--    the faithful match and preserves current behaviour exactly.
--    utf8mb4_bin exists in both MariaDB and MySQL. MariaDB 10.10+ also offers
--    utf8mb4_uca1400_as_cs (Unicode 14, accent- and case-sensitive), which is
--    closer to modern linguistic sorting — but utf8mb4_bin is the direct
--    analogue of SQLite's BINARY and is what this schema is written for.
--
--    Known residual difference: MariaDB's utf8mb4_bin is PAD SPACE, so in a
--    comparison 'bob' and 'bob ' are EQUAL there, whereas SQLite's BINARY
--    treats them as different lengths. **This is moot for this schema**: every
--    column under a unique constraint is either generated by the app (slug,
--    token, id) or trimmed before storage (member and category names — REG-024
--    verified "  Flights  " is stored as "Flights"). No trailing space can
--    reach a unique index. Noted only so it is not rediscovered as a mystery.
--
--    MariaDB 10.2+ also has NO PAD collations (named with an _nopad_ segment),
--    which would close that gap entirely. Whether a binary NO PAD variant
--    exists for utf8mb4 could not be confirmed from the docs, so this file does
--    not use one. If you want to check on your server:
--        SHOW COLLATION LIKE 'utf8mb4%nopad%';
--
-- If your host forces a database-level default collation you cannot change,
-- every table below pins its own charset/collation, so it still works.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- Group
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Group` (
  `id`        VARCHAR(191) NOT NULL,
  `slug`      VARCHAR(191) NOT NULL,
  `name`      VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `Group_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


-- ---------------------------------------------------------------------------
-- GroupMember
--   `token` is the per-member secret used by the /u/<token> invite link.
--   UNIQUE(groupId, name) is the constraint that collation point 2 above is
--   about — it is what stops duplicate member names within one group.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `GroupMember` (
  `id`        VARCHAR(191) NOT NULL,
  `token`     VARCHAR(191) NOT NULL,
  `name`      VARCHAR(191) NOT NULL,
  `groupId`   VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `GroupMember_token_key` (`token`),
  UNIQUE KEY `GroupMember_groupId_name_key` (`groupId`, `name`),
  CONSTRAINT `GroupMember_groupId_fkey`
    FOREIGN KEY (`groupId`) REFERENCES `Group` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


-- ---------------------------------------------------------------------------
-- Category
--   `emoji` holds the icon literally — see charset point 1 above.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Category` (
  `id`      VARCHAR(191) NOT NULL,
  `emoji`   VARCHAR(191) NOT NULL,
  `name`    VARCHAR(191) NOT NULL,
  `groupId` VARCHAR(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Category_groupId_name_key` (`groupId`, `name`),
  CONSTRAINT `Category_groupId_fkey`
    FOREIGN KEY (`groupId`) REFERENCES `Group` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


-- ---------------------------------------------------------------------------
-- Expense
--   `amount` is DECIMAL(12,2) — exact decimal, not a float. This is the
--   POST-MIGRATION target; see the MONEY note at the foot of this file before
--   pointing the app at it.
--
--   `splitType` is NULLABLE ON PURPOSE. It records which of the three split
--   modes the user chose ("equal" | "unequal" | "percentage"). Rows written
--   before the column existed carry no answer, and NULL means
--   "unknown — fall back to the share-shape heuristic", NOT "equal".
--   Do not add a default here; the distinction is load-bearing.
--
--   ON DELETE for paidBy is RESTRICT (Prisma's default for a required
--   relation), so a member who has paid an expense cannot be deleted.
--   categoryId is SetNull, so deleting a category leaves the expense intact.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Expense` (
  `id`          VARCHAR(191)  NOT NULL,
  `description` VARCHAR(191)  NOT NULL,
  `amount`      DECIMAL(12,2) NOT NULL,
  `paidById`    VARCHAR(191)  NOT NULL,
  `groupId`     VARCHAR(191)  NOT NULL,
  `categoryId`  VARCHAR(191)  NULL,
  `date`        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt`   DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `splitType`   VARCHAR(191)  NULL,
  PRIMARY KEY (`id`),
  KEY `Expense_groupId_createdAt_idx` (`groupId`, `createdAt`),
  KEY `Expense_paidById_idx` (`paidById`),
  KEY `Expense_categoryId_idx` (`categoryId`),
  CONSTRAINT `Expense_groupId_fkey`
    FOREIGN KEY (`groupId`) REFERENCES `Group` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Expense_paidById_fkey`
    FOREIGN KEY (`paidById`) REFERENCES `GroupMember` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Expense_categoryId_fkey`
    FOREIGN KEY (`categoryId`) REFERENCES `Category` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


-- ---------------------------------------------------------------------------
-- ExpenseShare
--   `percentage` is the whole-number percentage the user typed, stored for
--   "percentage" expenses only, and NULL everywhere else. It is kept alongside
--   `amount` because the dollar figure cannot be inverted back to the
--   percentage reliably (re-deriving it can land on 99% or 101% after rounding,
--   which would block the form from saving).
--
--   Both FKs are CASCADE: deleting an expense removes its shares, and removing
--   a member removes their shares.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExpenseShare` (
  `id`         VARCHAR(191)  NOT NULL,
  `expenseId`  VARCHAR(191)  NOT NULL,
  `memberId`   VARCHAR(191)  NOT NULL,
  `amount`     DECIMAL(12,2) NOT NULL,
  `percentage` DECIMAL(5,2)  NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ExpenseShare_expenseId_memberId_key` (`expenseId`, `memberId`),
  KEY `ExpenseShare_memberId_idx` (`memberId`),
  CONSTRAINT `ExpenseShare_expenseId_fkey`
    FOREIGN KEY (`expenseId`) REFERENCES `Expense` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ExpenseShare_memberId_fkey`
    FOREIGN KEY (`memberId`) REFERENCES `GroupMember` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


-- ---------------------------------------------------------------------------
-- Settlement
--   paidById is the member who PAID; receivedById is the member who RECEIVED.
--   Both are RESTRICT, so a member referenced by a settlement cannot be deleted.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Settlement` (
  `id`           VARCHAR(191)  NOT NULL,
  `groupId`      VARCHAR(191)  NOT NULL,
  `paidById`     VARCHAR(191)  NOT NULL,
  `receivedById` VARCHAR(191)  NOT NULL,
  `amount`       DECIMAL(12,2) NOT NULL,
  `createdAt`    DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `Settlement_groupId_createdAt_idx` (`groupId`, `createdAt`),
  KEY `Settlement_paidById_idx` (`paidById`),
  KEY `Settlement_receivedById_idx` (`receivedById`),
  CONSTRAINT `Settlement_groupId_fkey`
    FOREIGN KEY (`groupId`) REFERENCES `Group` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Settlement_paidById_fkey`
    FOREIGN KEY (`paidById`) REFERENCES `GroupMember` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Settlement_receivedById_fkey`
    FOREIGN KEY (`receivedById`) REFERENCES `GroupMember` (`id`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


-- ============================================================================
-- VERIFY — run this after the script and check both columns.
-- `emoji` must survive the round trip, and the collation must be utf8mb4_bin.
-- ============================================================================
-- SELECT VERSION();
--   ^ expect 11.1.5-MariaDB — confirm before trusting anything else here.
--
-- INSERT INTO `Group` (`id`,`slug`,`name`) VALUES ('probe','probe-slug','Probe 🍕 中文');
-- SELECT `name` FROM `Group` WHERE `slug` = 'probe';
--   ^ must return  Probe 🍕 中文  — if it returns "Probe ??" or errors, the
--     server is not actually storing utf8mb4 and everything else is moot.
--
-- SELECT TABLE_NAME, TABLE_COLLATION FROM information_schema.TABLES
--   WHERE TABLE_SCHEMA = DATABASE();
--   ^ every row must read utf8mb4_bin.
--
-- SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE FROM information_schema.COLUMNS
--   WHERE TABLE_SCHEMA = DATABASE() AND COLUMN_NAME IN ('amount','percentage');
--   ^ all four must read decimal(12,2); percentage reads decimal(5,2).
--     If any reads `double`, the wrong version of this file was loaded.
--
-- Decimal exactness probe — this is the whole point of the type change:
-- SELECT CAST('0.1' AS DECIMAL(12,2)) + CAST('0.2' AS DECIMAL(12,2)) = 0.3;
--   ^ must return 1. The float version of the same sum famously returns 0.
--
-- Case-sensitivity probe (should insert BOTH rows; a duplicate-key error here
-- means the collation is case-insensitive and the unique constraints are wrong):
-- INSERT INTO `Group` (`id`,`slug`,`name`) VALUES ('probe2','probe-slug-2','bob');
--   ...and a member named 'Bob' in the same group must be allowed alongside 'bob'.
-- DELETE FROM `Group` WHERE `slug` IN ('probe','probe-slug-2');


-- ============================================================================
-- MONEY — DECIMAL(12,2). READ BEFORE POINTING THE APP AT THIS DATABASE.
--
-- The four money columns are exact decimal:
--     Expense.amount           DECIMAL(12,2)
--     ExpenseShare.amount      DECIMAL(12,2)
--     ExpenseShare.percentage  DECIMAL(5,2)
--     Settlement.amount        DECIMAL(12,2)
--
-- WHY. Money was previously stored as Float, and the app's rounding idiom was
-- `Math.round(n * 100) / 100`, which is not exact. Measured against true
-- decimal rounding it disagrees on ordinary inputs:
--     Math.round(1.005 * 100) / 100  ->  1.00    but 1.005 to 2dp is 1.01
--     Math.round(4.015 * 100) / 100  ->  4.01    but 4.015 to 2dp is 4.02
-- so the effective rule was "whatever the binary representation happens to
-- do" — unreproducible, and reachable from an ordinary percentage split
-- (10% of $10.05 is exactly $1.005). DECIMAL removes the class entirely.
--
-- (12,2) is 10 integer digits + 2 decimal: up to 9,999,999,999.99. About $10bn
-- of headroom on a holiday-expenses app — you will never think about it again.
--
-- *** THE APP WILL NOT READ THIS CORRECTLY UNTIL THE REFACTOR LANDS. ***
-- Prisma returns DECIMAL as a Decimal OBJECT, not a JS number. Until the code
-- is refactored, this breaks:
--   - `a + b`: STRING CONCATENATION. 10.05 + 5.02 is "10.055.02", not 15.07.
--   - `a - b` / `a * n` / `a / n`: silently coerced through a float, so the
--     exactness is lost (10.05 - 5.02 is 5.030000000000001).
--   - `typeof x === "number"`: FALSE for every Decimal, with no error anywhere.
--     `edit/page.tsx`'s `typeof s.percentage === "number"` therefore silently
--     dropped stored percentages and invisibly regressed the S-2 fix. This is
--     the failure that produces no signal.
--   - JSON serialisation: a Decimal reaches the client as a STRING ("12.34").
--   - React server -> client props: a Decimal throws outright ("Only plain
--     objects can be passed to Client Components... Decimal objects are not
--     supported").
-- Use .plus() / .minus() / .times() / .comparedTo() / .toDecimalPlaces(2)
-- instead, and convert at the edges.
--
-- CORRECTED 2026-09-24, after this migration was implemented and measured on the
-- real stack (Prisma 6.19.3 / decimal.js). An earlier version of this note also
-- claimed Math.abs / Math.round / Math.min / Math.max "break", that
-- Intl.NumberFormat fails, and that .toFixed() throws. **They do not.** All of
-- them coerce through `valueOf()` (or, for toFixed, are Decimal methods in their
-- own right) and appear to work: Math.abs(Decimal) is 12.34, Intl formats a
-- Decimal to "$12.34", and `new Decimal("10.05").toFixed(2)` is "10.05". They are
-- the more dangerous paths precisely because they keep producing plausible
-- answers instead of errors, but they do not throw and do not return NaN. The
-- list above is the measured one; the helper that replaces them is `lib/money.ts`.
--
-- Measured scope of that refactor (2026-09-22): the money engine is 572 lines
-- across 5 files — lib/utils.ts, lib/balance.ts, lib/expense-shares.ts,
-- expenses/_actions.ts, settle/_actions.ts. There are 21 formatCurrency call
-- sites, all absorbed by making that one function accept Decimal; only 9
-- Prisma money reads; 16 landmine occurrences in total.
--
-- The Prisma schema must change to match, in the same pass:
--     provider    = "sqlite"  ->  "mysql"
--     amount      Float       ->  Decimal  @db.Decimal(12, 2)
--     percentage  Float?      ->  Decimal? @db.Decimal(5, 2)
-- Pin the precision explicitly: a bare Prisma `Decimal` maps to DECIMAL(65,30)
-- and `db pull` would widen these columns back to that.
--
-- LOADING THIS SCHEMA NOW IS FINE — it only creates tables. The app simply
-- must not be pointed at this database until the code is updated.
-- ============================================================================


-- ============================================================================
-- NOTE ON THE SERVER VERSION — 11.1.5-MariaDB-ubu2204
--
-- Nothing in this file depends on the version beyond MariaDB 10.0, so it will
-- run as-is. But MariaDB 11.1 is a SHORT-TERM release, not an LTS: it shipped
-- August 2023 and went end-of-life 21 August 2024. The final release in the
-- series was 11.1.6. This server is therefore running one patch behind a series
-- that has had no security updates for roughly two years.
--
-- That is not a schema problem and not a reason to change anything above — but
-- it is worth knowing before you put an app on it that friends will use, and it
-- is a fair question to put to whoever runs the host. If you ever control the
-- version, the LTS lines are 10.11 (supported to Feb 2028) and the newer LTS
-- series (11.4, 11.8).
--
-- I did NOT change any DDL over this. The schema above is correct on 11.1.5.
-- ============================================================================
